# Site settings
title: rotub*
email: rohan.nowell@gmail.com
description: "I'm a front end web developer at Virgin Mobile. When i'm not working i am watching Seinfeld reruns, science documentaries, and lots of movies. When I'm looking at a screen i am skateboarding or surfing."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
twitter_username: rotub
github_username:  rotub
permalink: /:title.html

# Build settings
markdown: kramdown
