# Site settings
title: rotub*
email: rohan.nowell@gmail.com
description: "I'm a front end web developer at Virgin Mobile. When i'm not make the web, i am TV (Seinfeld reruns, and science documentaries). I also love watching movies."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
twitter_username: rotub
github_username:  rotub
permalink: /:title.html

# Build settings
markdown: kramdown
